[tool.poetry]
name = "pytransferwise"
version = "0.1.3-dev"
description = "Python library for the TransferWise API"
authors = ["James Addison <jay@jp-hosting.net>"]
homepage = "https://www.github.com/jayaddison/pytransferwise"
repository = "https://www.github.com/jayaddison/pytransferwise"
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
apiron = "^5.0.0"
munch = "^2.5.0"
cryptography = "^2.8"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^5.3.5"
pytest-forked = "^1.1.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
