---
name: publish release
on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Ensure that the git tag is present for poetry-dynamic-versioning plugin to read
      - run: git fetch origin ${{ github.ref_name }}
      - uses: actions/setup-python@v2
      - run: pip install poetry
      - run: poetry install
      - run: poetry publish --build
